12 kakao login
zizon-developers/now-where-client pull request #19
Opened 2023-08-25 09:14 UTC by ohs8283

카카오 로그인 기능 추가를 하였는데 현재는 기능적인 면만 두어 PR을 보냈습니다ㅠ 디자인 요소와 나머지 세부 사항은 추후에 빨리 작업할 수 있도록 하겠습니다.

- 카카오 로그인 기능 추가: 사용자가 카카오 계정을 통해 로그인할 수 있도록 구현했습니다.
- 간단한 버튼 추가: 현재 버튼 디자인은 아직 처리하지 않았는데 추후에 디자인을 개선할 예정입니다.

2023-08-25 09:21 UTC, m1nsuplee requested changes

2023-08-25 09:21 UTC, m1nsuplee commented on app/src/App.tsx
> +          path="/"
로그인 페이지의 path는 `/login`이 좋을 것 같음

2023-08-25 09:21 UTC, m1nsuplee commented on app/src/App.tsx
> +    <>
이건 왜 쓴 거임?

2023-08-25 09:21 UTC, m1nsuplee commented on app/src/pages/KakaoOAuthRedirectPage.tsx
> +type LoginResponse = {
`types`라는 디렉토리가 있습니다. 옮깁시다~

2023-08-25 09:21 UTC, m1nsuplee commented on app/src/pages/KakaoOAuthRedirectPage.tsx
> +  useEffect(() => {
이렇게 axios를 통해 http 요청을 하게 되면 http 요청이 두 번 진행됩니다.

한 번으로 줄일 수 있는 방법을 찾아야겠죠?

2023-08-25 09:21 UTC, m1nsuplee commented on app/src/pages/LoginPage.tsx
> +    <>
여기도 이거 왜 쓰는 거임? 쓸 이유가 없어보이는데

2023-08-25 09:21 UTC, m1nsuplee commented on app/src/pages/LoginPage.tsx
> +  const Rest_api_key = '867de5dcb061c1d22c4188893654cddb'; //REST API KEY
이런 보안 사항들을 다 노출...

2023-08-25 11:57 UTC, ohs8283 commented on app/src/App.tsx
> +          path="/"
[1036ffe](https://github.com/zizon-developers/now-where-client/pull/19/commits/1036ffec48c2ad59f5ff7395a53632460a5bab32)

2023-08-25 11:57 UTC, ohs8283 commented on app/src/App.tsx
> +    <>
[1036ffe](https://github.com/zizon-developers/now-where-client/pull/19/commits/1036ffec48c2ad59f5ff7395a53632460a5bab32)

2023-08-25 11:58 UTC, ohs8283 commented on app/src/pages/KakaoOAuthRedirectPage.tsx
> +type LoginResponse = {
[1dfe9ae](https://github.com/zizon-developers/now-where-client/pull/19/commits/1dfe9aed3bbcac6d1153f8b2e1290cc88eb004b7)

2023-08-25 11:58 UTC, ohs8283 commented on app/src/pages/KakaoOAuthRedirectPage.tsx
> +  useEffect(() => {
[07f3fa6](https://github.com/zizon-developers/now-where-client/pull/19/commits/07f3fa616d4c7ed810f281d83fa86114ef15a48d)

2023-08-25 12:15 UTC, m1nsuplee requested changes
아직 바꾸어야 할 내용들이 존재하는 것 같아

다시 참고해서 바꿔주고, 시크릿 키 여전히 노출되어있음

2023-08-25 12:15 UTC, m1nsuplee commented on app/src/types/loginTypes.ts
타입의 이름은 카멜 로우 케이스로 명명하지 않아용 다시 찾아보면 좋을 것 같음여

2023-08-25 12:15 UTC, m1nsuplee commented on app/src/pages/KakaoOAuthRedirectPage.tsx
> +  }, [code]); // code가 변경될 때에만 실행
굳이 주석을 쓸 이유는 없을 것 같음

주석은 복잡한 로직을 다룰 때에만 쓰는 것이 좋고, 그마저도 없는 것이 좋다고 봄

2023-08-25 12:17 UTC, m1nsuplee commented on app/src/pages/KakaoOAuthRedirectPage.tsx
> +  }, [code]); // code가 변경될 때에만 실행
그리고 우리 처음에 시작할 때 상태관리 라이브러리로 `react-query` 쓰기로 했으니까 그걸 이용해서 http 요청을 한 번으로 줄일 수 있을 것 같음

react-query가 어떻게 http 요청을 한 번만 수행하는지는 따로 찾아보면 좋을 듯

2023-08-25 22:29 UTC, ohs8283 commented on app/src/pages/LoginPage.tsx
> +  const Rest_api_key = '867de5dcb061c1d22c4188893654cddb'; //REST API KEY
gpt나 인터넷 찾아봤는데 .env 파일을 생성하고 시크릿 키를 환경 변수로 설정하고 gitignore파일에 .env추가하는 방법밖에 모르겠어서 어떻게 해야할지 모르겠어요 ㅠㅠ

2023-08-25 22:36 UTC, m1nsuplee requested changes

2023-08-25 22:36 UTC, m1nsuplee commented on app/src/pages/LoginPage.tsx
> +  const Rest_api_key = '867de5dcb061c1d22c4188893654cddb'; // REST API KEY
이거 여전히 노출되어 있습니다

2023-08-25 22:36 UTC, m1nsuplee commented on app/package.json
> +    "react-icons": "^4.10.1",
카카오 로그인 아이콘 때문에 이걸 설치하기에는 이게 너무 무거운 것 같아

이렇게 라이브러리를 사용하는 방법 말고 피그마에 있는 이미지를 추출하는 방법을 사용하는게 어떨까싶어

2023-08-25 23:11 UTC, m1nsuplee commented on app/src/pages/LoginPage.tsx
> +  const Rest_api_key = '867de5dcb061c1d22c4188893654cddb'; //REST API KEY
> gpt나 인터넷 찾아봤는데 .env 파일을 생성하고 시크릿 키를 환경 변수로 설정하고 gitignore파일에 .env추가하는 방법밖에 모르겠어서 어떻게 해야할지 모르겠어요 ㅠㅠ

ㅇㅇ 그렇게 하는 거 맞는디용

2023-08-25 23:15 UTC, m1nsuplee requested changes
변경해야할 점

1. 로그인 페이지에서 사용할 카카오 아이콘을 위해 `react/icons`라는 라이브러리를 설치했는데 이것보단 그냥 카카오 로고 svg 파일을 쓰는게 나아보임
-  (이유는 그 라이브러리 무게가 말도 안되게 큼)
2. 유출되지 말아야 할 정보들 `.env`로 관리하기 
  - 제 생각에는 vite 공식 문서를 참고하는게 좋아보임 `.env.local` 파일과 `.env.example`을 같이 만들고, 따로 개인적으로 키값들을 알려주는 방식
3. `loginType.ts` 라는 파일의 이름을 좀 더 고민해보기

2023-08-26 11:41 UTC, m1nsuplee requested changes

2023-08-26 11:41 UTC, m1nsuplee commented on app/src/services/auth.ts
> +  console.log(headers.authorization, headers['Authorization'], headers.Authorization);
현우가 서버에서 헤더 접근 가능하게 열어저숴 여기 부분에서 `headers.authorization` 접근하면 됨
참고로 대소문자 구분 확실히!

2023-08-27 08:05 UTC, ohs8283 commented on app/src/services/auth.ts
> +  console.log(headers.authorization, headers['Authorization'], headers.Authorization);
![image](https://github.com/zizon-developers/now-where-client/assets/110721887/3ec3ff9c-cbdf-417b-9d33-f8e9daf68644)
요로코롬??

2023-08-27 08:06 UTC, m1nsuplee commented on app/src/services/auth.ts
> +  console.log(headers.authorization, headers['Authorization'], headers.Authorization);
> ![image](https://user-images.githubusercontent.com/110721887/263515737-3ec3ff9c-cbdf-417b-9d33-f8e9daf68644.png) 요로코롬??

ㅇㅇ 귣👍

2023-08-27 13:54 UTC, m1nsuplee approved these changes
LGTM🚀

2023-08-27 14:00 UTC, merged

2023-08-27 15:39 UTC, m1nsuplee commented on app/src/services/index.ts
> +    withCredentials: true,
`withCredential` 속성 true로 하면, 서버 쪽에서 응답이 제대로 안내려지는 것 같은데 현우랑 얘기해서 `Exposed-Header` 설정을 바꿀 것인지 `Credential` 속성을 바꿀 것인지 합의보세요