[ADD]eslint,prettier
zizon-developers/now-where-client pull request #3
Opened 2023-08-09 15:34 UTC by ohs8283

2023-08-09 15:44 UTC, rocky-at-planningo requested changes

2023-08-09 15:44 UTC, rocky-at-planningo commented on package.json
>    "devDependencies": {
`scss`를  root directory에서도 설치해야하나요??

RN에서는 scss를 쓰지 않는데 이게 공유되어야하나합니다.

2023-08-11 12:48 UTC, m1nsuplee commented on package.json
> +    "node-sass": "^9.0.0",
node-sass를 써야만 scss를 쓸 수 있나요?

2023-08-11 12:48 UTC, m1nsuplee commented on package.json
> +    "eslint": "^8.46.0",
eslint도 협의 후에 설정하시는 걸로..

2023-08-11 12:58 UTC, m1nsuplee requested changes
main이 아닌 `develop` 브랜치로 PR 요청하고, 아까 말했던 scss를 쓸 이유보다 tailwindcss를 쓸 이유가 더 크기 떄문에 tailwindcss config한 내용으로 다시 PR ㄱㄱㄱ🚀

2023-08-11 14:21 UTC, closed without merging